[package]
name = "python_compiler"
version = "0.1.0"
authors = ["Shing Lyu <shing.lyu@gmail.com>"]

[dependencies]
cpython = { git = "https://github.com/dgrunwald/rust-cpython.git" }

[dependencies.python27-sys]
version = "*"
